cache: packages
sudo: required
warnings_are_errors: true
os: linux
dist: xenial
language: r
before_install:
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y libgdal1-dev
  - sudo apt-get install -y libharfbuzz-dev
  - sudo apt-get install -y libfribidi-dev
  - sudo apt-get install -y libgit2-dev
r:
- bioc-release
#r_packages:
#  - covr
r_github_packages:
- cole-trapnell-lab/leidenbase
#r_binary_packages:
r_packages:
 - covr
 - assertthat
 - dplyr
 - devtools
 - ggplot2
 - ggrastr
 - ggrepel
 - igraph
 - irlba
 - lmtest
 - MASS
 - Matrix
 - pbapply
 - pbmcapply
 - pheatmap
 - plotly
 - plyr
 - proxy
 - pryr
 - pscl
 - purrr
 - RANN
 - Rcpp
 - reshape2
 - RhpcBLASctl
 - roxygen2
 - shiny
 - slam
 - spdep
 - speedglm
 - stringr
 - tibble
 - tidyr
 - viridis

before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  - R CMD build --no-build-vignettes .
  - R CMD INSTALL ${PKG_TARBALL}
  - rm ${PKG_TARBALL}
  - echo "Session info:"
  - Rscript -e "library(${PKG_NAME});devtools::session_info('${PKG_NAME}')"

script:
  - |
    R CMD build .
    travis_wait 20 R CMD check monocle3*tar.gz

after_failure:
- Rscript -e 'devtools::install();devtools::test()'

notifications:
  slack:
    secure: FH+TwlrNXm1q2RGtIfVJn0pUfzlR9WXRE6mPYLy2y3mRjX+Uo4g6nG2X2cNUXQLapVjb6UWb5plJfDaajUr1AMdnRo9PcgxcRiYDLEaR/yiRPNp7p6rnC7mEbMDywincdGy9g/OhiTLqgwWwE925b9Mpim7zTGDE0Du4dz3VNUm6aQi1xY/S2LT8xnL1Y4/LyYwGzWSy6kyxRgxNKlIDVs28m7cER9xWzTFG0LG3VcWupPujRWYFV3JDuqMp6m4jWQ7gq4v0PIgyj+unZaa2eyE288E9xp5knhgZzvooN0P0IODnLF4GIBh48iyMuapllx1oaDEHRtjOWCljPugNLK1KQrSrnB95o/2BL3d0WtNv40nteaPP7Fed1+NfF2Zu11nSIfbc1fA1gXdk/AriYHalMmdsp45q3EVx3tkJ4bwcU0ox00HbVUJfeAhb/NwOkZzw1+jHSwB61SxRpyaTi81O3vKcBIxRKD+R1GFOYgGOafqqbf/GHsBFJH718iUyih2WV1Y+HktqbZ+yrViyuO/4Gmf352eq4gsvKJ5Kdap9xAjFyQMXrVFJ7Nm4q81z+r3/xs59fWuQyY+LXYyHYy0xygeinM/fAd2oTweeIR4y4DTBR5t673PPh3PC64xGDE3u29LUAcva5xOqUtdvuPM+2wLAHs8qqpqg+yS9aEo=

