# Notes:
#   o  add Rscript -e 'devtools::install_version("locfit", version="1.5-9.4")' because the new 1.5-9.5 version
#      requires >= R 4.1.0
#   o  add Rscript -e 'devtools::install_github('r-spatial/sf') because the current sf version (1.0-6) does
#      not build.
#   o  add lines to before_install in order to install recent cmake version, which is required by the recent
#      nloptr version. These lines are
#        - sudo wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
#        - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
#        - sudo apt-get update
#        - sudo apt-get install -y cmake

---
cache: packages
sudo: required
warnings_are_errors: true
os: linux
dist: xenial
language: r
before_install:
 - sudo apt-get install -y libnlopt-dev
 - sudo apt-get install -y libudunits2-dev
 - sudo apt-get install -y gdal-bin
 - sudo apt-get install -y libgdal1-dev
 - sudo apt-get install -y libharfbuzz-dev
 - sudo apt-get install -y libfribidi-dev
 - sudo apt-get install -y libgit2-dev
 - sudo wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
 - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
 - sudo apt-get update
 - sudo apt-get install -y cmake
r:
 - bioc-release
before_script:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install_version("locfit", version="1.5-9.4")'
  - Rscript -e 'devtools::install_github("r-spatial/sf")'
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  - R CMD build --no-build-vignettes .
  - R CMD INSTALL ${PKG_TARBALL}
  - rm ${PKG_TARBALL}
  - echo "Session info:"
  - Rscript -e "library(${PKG_NAME});devtools::session_info('${PKG_NAME}')"
  - Rscript -e "library(${PKG_NAME});devtools::session_info()"

script:
  - |
    export _R_CHECK_DONTTEST_EXAMPLES_=false
    R CMD build .
    export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
    if [ ! -f "$PKG_TARBALL" ]; then exit 1; fi
    travis_wait 20 R CMD check monocle3*tar.gz

after_failure:
 - Rscript -e 'devtools::install();devtools::test()'

notifications:
  slack:
    secure: FH+TwlrNXm1q2RGtIfVJn0pUfzlR9WXRE6mPYLy2y3mRjX+Uo4g6nG2X2cNUXQLapVjb6UWb5plJfDaajUr1AMdnRo9PcgxcRiYDLEaR/yiRPNp7p6rnC7mEbMDywincdGy9g/OhiTLqgwWwE925b9Mpim7zTGDE0Du4dz3VNUm6aQi1xY/S2LT8xnL1Y4/LyYwGzWSy6kyxRgxNKlIDVs28m7cER9xWzTFG0LG3VcWupPujRWYFV3JDuqMp6m4jWQ7gq4v0PIgyj+unZaa2eyE288E9xp5knhgZzvooN0P0IODnLF4GIBh48iyMuapllx1oaDEHRtjOWCljPugNLK1KQrSrnB95o/2BL3d0WtNv40nteaPP7Fed1+NfF2Zu11nSIfbc1fA1gXdk/AriYHalMmdsp45q3EVx3tkJ4bwcU0ox00HbVUJfeAhb/NwOkZzw1+jHSwB61SxRpyaTi81O3vKcBIxRKD+R1GFOYgGOafqqbf/GHsBFJH718iUyih2WV1Y+HktqbZ+yrViyuO/4Gmf352eq4gsvKJ5Kdap9xAjFyQMXrVFJ7Nm4q81z+r3/xs59fWuQyY+LXYyHYy0xygeinM/fAd2oTweeIR4y4DTBR5t673PPh3PC64xGDE3u29LUAcva5xOqUtdvuPM+2wLAHs8qqpqg+yS9aEo=

